-- 创建工作记录表
create table public.work_records (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  total_hours numeric not null,
  total_salary numeric not null,
  note text
);

-- 启用 Row Level Security (RLS)
alter table public.work_records enable row level security;

-- 创建策略：允许所有用户查看记录（由于没有做用户系统，这里为了演示方便开放权限，生产环境建议配合 Auth 使用）
create policy "Allow public access to work_records"
on public.work_records
for all
using (true)
with check (true);

-- 创建策略：允许所有用户插入记录
create policy "Allow public insert to work_records"
on public.work_records
for insert
with check (true);

-- 创建策略：允许所有用户删除记录
create policy "Allow public delete to work_records"
on public.work_records
for delete
using (true);
