-- 创建主播表
create table public.anchors (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null
);

-- 启用 Row Level Security (RLS)
alter table public.anchors enable row level security;

-- 创建策略：允许所有用户访问主播表
create policy "Allow public access to anchors"
on public.anchors
for all
using (true)
with check (true);

-- 创建工作记录表
create table public.work_records (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  total_hours numeric not null,
  total_salary numeric not null,
  note text,
  anchor_id bigint references public.anchors(id) on delete set null
);

-- 启用 Row Level Security (RLS)
alter table public.work_records enable row level security;

-- 创建策略：允许所有用户查看记录
create policy "Allow public access to work_records"
on public.work_records
for all
using (true)
with check (true);

-- 创建策略：允许所有用户插入记录
create policy "Allow public insert to work_records"
on public.work_records
for insert
with check (true);

-- 创建策略：允许所有用户删除记录
create policy "Allow public delete to work_records"
on public.work_records
for delete
using (true);
